"""empty message

Revision ID: 99304aedead0
Revises: a32682a7efaa
Create Date: 2021-02-12 20:03:06.953794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99304aedead0'
down_revision = 'a32682a7efaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region')
    # ### end Alembic commands ###
